<div class="panel panel-default">
    <div class="panel-heading">
        Dev Tools - Dashboard
    </div>
    <div class="panel-body">
        <div class="col-xs-4">
            <h4>Entidades</h4>
            <table class="table table-bordered table-condensed table-hover table-responsive table-striped">
                <thead>
                    <tr>
                        <th>Nome</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>\Admin\Entity\User</td>
                    </tr>
                    <tr>
                        <td>\Admin\Entity\UserGroup</td>
                    </tr>
                    <tr>
                        <td>\Admin\Entity\Access</td>
                    </tr>
                    <tr>
                        <td>\Admin\Entity\AccessGroup</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>