<style>
    #kf-dev-toolbar .navbar-brand {
        background: none;
        height: auto;
        text-indent: 0;
        width: auto;
    }
    body > .container {
        margin-bottom: 80px;
    }
</style>
<div id="kf-dev-toolbar"  class="navbar navbar-inverse navbar-fixed-bottom">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->basePath ?>kf-dev-tools/dev-tools/index">DevTools</a>
        </div>
    </div>
</div>